dataset_name: "global-pcodes"

resource_name:
  all: "global_pcodes.csv"
  adm_12: "global_pcodes_adm_1_2.csv"
  lengths: "global_pcode_lengths.csv"

resource_exceptions: {}

non_latin_alphabets:
  - "ar"
  - "bg"
  - "da"
  - "el"
  - "fa"
  - "ka"
  - "ky"
  - "lo"
  - "mn"
  - "ru"
  - "si"
  - "ta"
  - "th"
  - "ua"
  - "vi"

missing_units:
  SSD:
    Abyei:
      Location: "SSD"
      Admin Level: "1"
      P-Code: "SS00"
      Name: "Abyei Region"
      Parent P-Code: "SSD"
      Valid from date: "2023-08-29"
